const {chromium}=require('/Users/Nicolas/Documents/github/hermes/tontoko-jeev-browser/node_modules/playwright-core');
const assert=require('node:assert/strict'),fs=require('fs');
(async()=>{
const browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1280,height:900},acceptDownloads:true});
try {
const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
await page.route('**/recovered.html',async route=>{const r=await route.fetch();let html=await r.text();html=html.replace('window.__recBoot.ok();await loadCar();',`window.probe=()=>({selected:selected?.code,meshes:loaded?.meshes.map(m=>({base:m.userData.baseMaterial,map:loaded.textures.indexOf(m.material.map),filters:m.material.map?{min:m.material.map.minFilter,mag:m.material.map.magFilter,mips:m.material.map.generateMipmaps}:null,color:m.material.color.toArray(),factor:loaded.doc.materials[m.userData.baseMaterial].pbrMetallicRoughness,expectedMap:(()=>{const v=document.querySelector('#variant').value;const mapping=v===''?null:m.userData.variantMappings.find(x=>x.variants.includes(Number(v)));const pbr=loaded.doc.materials[mapping?mapping.material:m.userData.baseMaterial].pbrMetallicRoughness;return pbr.baseColorTexture===undefined?-1:loaded.doc.textures[pbr.baseColorTexture.index].source;})()})),doc:loaded?.doc,memory:renderer.info.memory});window.__recBoot.ok();await loadCar();`);await route.fulfill({response:r,body:html});});
await page.goto('http://127.0.0.1:8087/recovered.html');await page.waitForFunction(()=>window.probe?.().selected==='GRAN_TORINO');
const base=await page.evaluate(()=>{const p=probe();return {selected:p.selected,wrongMaps:p.meshes.filter(m=>m.map!==m.expectedMap).length,blackHeaders:p.meshes.filter(m=>m.factor.baseColorFactor?.slice(0,3).every(c=>c===0)).map(m=>m.color),memory:p.memory}});assert.equal(base.wrongMaps,0);assert(base.blackHeaders.length>0);assert(base.blackHeaders.every(c=>c.every(v=>v===0)));console.log('E01 corrected material',JSON.stringify({...base,blackHeaders:base.blackHeaders.length}));
assert(await page.evaluate(()=>probe().meshes.filter(m=>m.filters).every(m=>m.filters.min===1006&&m.filters.mag===1006&&!m.filters.mips)));
await page.locator('#sharp').check();assert(await page.evaluate(()=>probe().meshes.filter(m=>m.filters).every(m=>m.filters.min===1003&&m.filters.mag===1003&&!m.filters.mips)));
await page.locator('#sharp').uncheck();assert(await page.evaluate(()=>probe().meshes.filter(m=>m.filters).every(m=>m.filters.min===1006&&m.filters.mag===1006&&!m.filters.mips)));console.log('E13 captured linear/no-mip default and Sharp pixels round trip passed');
await page.screenshot({path:'.scratch/adversarial-2026-10-08/after-desktop.png'});
const download=page.waitForEvent('download');await page.locator('#download').click();const d=await download;await d.saveAs('.scratch/adversarial-2026-10-08/download.glb');assert.deepEqual(fs.readFileSync('.scratch/adversarial-2026-10-08/download.glb'),fs.readFileSync('viewer/public/recovered/GRAN_TORINO.glb'));console.log('E05 download byte-identical and parseable',fs.statSync('.scratch/adversarial-2026-10-08/download.glb').size);
await page.route('**/COBRA.glb',route=>route.fulfill({status:404,body:'missing'}));await page.selectOption('#car','COBRA');await page.waitForFunction(()=>document.querySelector('#retry').hidden===false);
const fail=await page.evaluate(()=>({car:document.querySelector('#car').value,shown:probe().selected??null,download:document.querySelector('#download').getAttribute('href'),recordEnabled:!document.querySelector('#record').disabled,status:document.querySelector('#status').textContent}));assert.equal(fail.shown,null);assert.equal(fail.download,null);assert.equal(fail.recordEnabled,false);console.log('E02 failed switch',JSON.stringify(fail));await page.screenshot({path:'.scratch/adversarial-2026-10-08/after-failed.png'});
await page.unroute('**/COBRA.glb');await page.locator('#retry').click();await page.waitForFunction(()=>probe().selected==='COBRA');assert.equal(await page.locator('#error').innerText(),'');console.log('E03 same-car retry passed');
let release;const block=new Promise(r=>release=r);await page.route('**/FOCUS_WRC.glb',async route=>{await block;await route.continue().catch(()=>{});});await page.selectOption('#car','FOCUS_WRC');await page.selectOption('#car','F350');await page.waitForFunction(()=>probe().selected==='F350');release();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>probe().selected),'F350');await page.unroute('**/FOCUS_WRC.glb');console.log('E06 delayed obsolete selection cannot overwrite F350');
await page.route('**/GT90.glb',route=>route.fulfill({status:200,body:Buffer.from('bad')}));await page.selectOption('#car','GT90');await page.waitForFunction(()=>document.querySelector('#retry').hidden===false);assert.match(await page.locator('#error').innerText(),/Truncated GLB header/);await page.unroute('**/GT90.glb');console.log('E07 malformed GLB failure is actionable');
await page.route('**/FORD_GT.glb',async route=>{await new Promise(r=>setTimeout(r,5500));await route.continue();});await page.selectOption('#car','FORD_GT');await page.waitForFunction(()=>probe().selected==='FORD_GT');assert.equal(await page.locator('#error').innerText(),'');await page.unroute('**/FORD_GT.glb');console.log('E08 5.5s valid load no false startup error');
let releaseTimeout;const stall=new Promise(r=>releaseTimeout=r);await page.route('**/GT90.glb',async route=>{await stall;await route.continue().catch(()=>{});});await page.selectOption('#car','GT90');await page.waitForFunction(()=>document.querySelector('#retry').hidden===false);assert.match(await page.locator('#error').innerText(),/timed out/);releaseTimeout();await page.unroute('**/GT90.glb');console.log('E11 stalled request times out with retry after 15s');
const corrupt=fs.readFileSync('viewer/public/recovered/COBRA.glb');const jsonSize=corrupt.readUInt32LE(12);const doc=JSON.parse(corrupt.subarray(20,20+jsonSize));const offset=28+jsonSize+doc.bufferViews[doc.images[0].bufferView].byteOffset;corrupt.fill(0,offset,offset+8);await page.route('**/COBRA.glb',route=>route.fulfill({status:200,body:corrupt}));await page.selectOption('#car','COBRA');await page.waitForFunction(()=>document.querySelector('#retry').hidden===false);assert.match(await page.locator('#error').innerText(),/Embedded texture/);assert.equal(await page.locator('#download').getAttribute('href'),null);await page.unroute('**/COBRA.glb');console.log('E12 corrupted embedded PNG rejected without stale download');

const cars=JSON.parse(fs.readFileSync('viewer/public/recovered/index.json')).cars;let wrongMaps=0,variants=0;const start=Date.now();
for(const car of cars){console.log('corpus start',car.code);await page.selectOption('#car',car.code);await page.waitForFunction(code=>probe().selected===code,car.code,{timeout:10000}).catch(async error=>{console.log('corpus failure',await page.locator('#error').innerText());throw error;});wrongMaps+=await page.evaluate(()=>{const p=probe();return p.meshes.filter(m=>m.map!==m.expectedMap).length;});const options=await page.locator('#variant option').evaluateAll(xs=>xs.map(x=>x.value));for(const v of options.filter(Boolean)){await page.selectOption('#variant',v);variants++;const failures=await page.evaluate(()=>{return probe().meshes.filter(m=>m.map!==m.expectedMap).length;});assert.equal(failures,0);} }
console.log('E09 corpus traversal',JSON.stringify({cars:cars.length,wrongMaps,variants,elapsedMs:Date.now()-start,memory:await page.evaluate(()=>probe().memory)}));
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'.scratch/adversarial-2026-10-08/after-mobile.png'});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert.equal(overflow,0);console.log('E10 mobile overflow',overflow);await page.locator('#stage').scrollIntoViewIfNeeded();await page.screenshot({path:'.scratch/adversarial-2026-10-08/after-mobile-stage.png'});
await page.goto('http://127.0.0.1:8087/');await page.waitForSelector('.car-row');assert.equal(await page.locator('.car-row').evaluateAll(xs=>xs.filter(x=>x.tabIndex>=0).length),35);const first=page.locator('.car-row').first();await first.focus();await page.keyboard.press('Enter');assert.equal(await first.getAttribute('aria-pressed'),'true');const chip=page.locator('.chip').first();await chip.focus();await page.keyboard.press('Space');assert.equal(await chip.getAttribute('aria-pressed'),'true');await page.keyboard.press('Space');assert.equal(await chip.getAttribute('aria-pressed'),'false');await page.locator('#search').fill('no-such-car');assert.equal(await page.locator('.car-row:visible').count(),0);await page.locator('#search').fill('');assert.equal(await page.locator('.car-row:visible').count(),35);console.log('E04 gallery keyboard car/filter activation and search recovery passed');await page.screenshot({path:'.scratch/adversarial-2026-10-08/gallery-mobile.png'});
assert.deepEqual(errors,[]);assert(requests.filter(u=>!u.startsWith('blob:')).every(u=>u.startsWith('http://127.0.0.1:8087/')));console.log('pageErrors',errors,'all requests local');} finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
