
import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const stage=document.querySelector('#stage'), carSelect=document.querySelector('#car'), recordSelect=document.querySelector('#record'), status=document.querySelector('#status');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));stage.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#151a22');
const camera=new THREE.PerspectiveCamera(40,1,.01,2000);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new THREE.HemisphereLight(0xe8f4ff,0x3c4659,2));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(5,8,4);scene.add(key);
let loaded=null, selected=null, requestId=0;
function dispose(){if(!loaded)return;for(const m of loaded.meshes){m.geometry.dispose();m.material.dispose();}for(const t of loaded.textures)t.dispose();for(const u of loaded.urls)URL.revokeObjectURL(u);for(const g of loaded.groups)scene.remove(g);loaded=null;}
function readGLB(buffer){
 const head=new DataView(buffer);if(head.getUint32(0,true)!==0x46546c67||head.getUint32(4,true)!==2||head.getUint32(8,true)!==buffer.byteLength)throw Error('Invalid GLB header');
 let cursor=12,doc,bin;while(cursor<buffer.byteLength){const size=head.getUint32(cursor,true),kind=head.getUint32(cursor+4,true);if(cursor+8+size>buffer.byteLength)throw Error('Truncated GLB');if(kind===0x4e4f534a)doc=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,cursor+8,size)));if(kind===0x004e4942)bin=buffer.slice(cursor+8,cursor+8+size);cursor+=8+size;}if(!doc||!bin)throw Error('Missing GLB chunks');
 return {doc,bin};
}
async function loadCar(){
 const id=++requestId;status.textContent='Loading '+carSelect.value+'…';document.querySelector('#error').textContent='';
 try{const entry=index.cars.find(c=>c.code===carSelect.value);const response=await fetch('public/recovered/'+entry.file);if(!response.ok)throw Error('Geometry file unavailable');const {doc,bin}=readGLB(await response.arrayBuffer());if(id!==requestId)return;dispose();
 const state={groups:[],meshes:[],textures:[],urls:[]};loaded=state;selected=entry;
 function values(i){const a=doc.accessors[i],v=doc.bufferViews[a.bufferView],n={SCALAR:1,VEC2:2,VEC3:3}[a.type];const Type=a.componentType===5125?Uint32Array:Float32Array;return new Type(bin,(v.byteOffset||0)+(a.byteOffset||0),a.count*n);}
 const loader=new THREE.TextureLoader();
 for(const image of doc.images){const v=doc.bufferViews[image.bufferView],url=URL.createObjectURL(new Blob([new Uint8Array(bin,v.byteOffset||0,v.byteLength)],{type:'image/png'}));state.urls.push(url);const texture=loader.load(url);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.flipY=false;texture.magFilter=THREE.NearestFilter;state.textures.push(texture);}
 for(const node of doc.nodes){if(node.extras.assemblyCandidate)continue;const group=new THREE.Group();group.visible=false;group.userData.record=String(node.extras.geometryRecord);for(const p of doc.meshes[node.mesh].primitives){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(values(p.attributes.POSITION),3));geometry.setAttribute('normal',new THREE.BufferAttribute(values(p.attributes.NORMAL),3));if(p.attributes.TEXCOORD_0!==undefined)geometry.setAttribute('uv',new THREE.BufferAttribute(values(p.attributes.TEXCOORD_0),2));geometry.setIndex(new THREE.BufferAttribute(values(p.indices),1));const material=new THREE.MeshStandardMaterial({map:state.textures[p.material]||null,color:state.textures[p.material]?0xffffff:0xaab6c8,roughness:1,metalness:0,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geometry,material);mesh.userData.candidateMap=material.map;group.add(mesh);state.meshes.push(mesh);}scene.add(group);state.groups.push(group);}
 function treeNode(index){const node=doc.nodes[index];const base=state.groups.find(g=>g.userData.record===String(node.extras.geometryRecord));const group=base?base.clone(true):new THREE.Group();group.visible=true;group.position.fromArray(node.translation||[0,0,0]);for(const child of node.children||[])group.add(treeNode(child));return group;}
 for(const a of entry.assemblies||[]){const tree=treeNode(a.rootNode);tree.userData.record='tree'+a.tree;tree.visible=false;scene.add(tree);state.groups.push(tree);}
 recordSelect.replaceChildren(...(entry.assemblies||[]).map(a=>{const o=document.createElement('option');o.value='tree'+a.tree;o.textContent=`Tree ${a.tree} — all runtime states`;return o;}),...entry.records.map(r=>{const o=document.createElement('option');o.value=String(r.record);o.textContent=`Record ${r.record}: ${r.triangles.toLocaleString()} candidate triangles`;return o;}));recordSelect.value=entry.assemblies?.length?'tree0':String(entry.records[0].record);
 document.querySelector('#download').href='public/recovered/'+entry.file;showRecord();
 }catch(e){if(id===requestId){status.textContent='Geometry could not be loaded.';document.querySelector('#error').textContent=e.message;}}
}
function updateMaterials(){if(!loaded)return;for(const m of loaded.meshes){m.material.map=document.querySelector('#textures').checked?m.userData.candidateMap:null;m.material.wireframe=document.querySelector('#wire').checked;m.material.needsUpdate=true;}for(const t of loaded.textures){t.flipY=document.querySelector('#flip').checked;t.needsUpdate=true;}}
function showRecord(){if(!loaded)return;const n=recordSelect.value;for(const g of loaded.groups)g.visible=g.userData.record===n;const group=loaded.groups.find(g=>g.visible);if(!group)return;const box=new THREE.Box3().setFromObject(group),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()),extent=Math.max(size.x,size.y,size.z,.1);controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(extent*.95,extent*.55,extent*.95));camera.near=Math.max(extent/10000,.0001);camera.far=extent*100;camera.updateProjectionMatrix();controls.update();updateMaterials();const r=selected.records.find(r=>String(r.record)===n);status.textContent=`${selected.code} · ${n.startsWith('tree')?'candidate tree '+n.slice(4)+' · all runtime states':`record ${n} · ${r.triangles.toLocaleString()} candidate triangles`} · bounds ${size.toArray().map(v=>v.toFixed(3)).join(' × ')} · runtime selection pending`;}
const index=await(await fetch('public/recovered/index.json')).json();for(const c of index.cars){const o=document.createElement('option');o.value=c.code;o.textContent=c.code.replaceAll('_',' ');carSelect.append(o);}carSelect.value='GRAN_TORINO';carSelect.addEventListener('change',loadCar);recordSelect.addEventListener('change',showRecord);for(const id of ['textures','wire','flip'])document.querySelector('#'+id).addEventListener('change',updateMaterials);
new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();}).observe(stage);renderer.setAnimationLoop(()=>{controls.update();renderer.render(scene,camera);});await loadCar();
